### PR TITLE
Creation

### PR DESCRIPTION
**Pull request by Tex2063**
Created Folders and Files for Assets, Images, and JavaScript..

### CODE REVIEW

**Comment by Tex2063** [comment]
Still waiting on this to be approved and committed to master branch.

**Comment by Tex2063** [comment]
Created initial layout for input and results. Please review.

**Comment by Tex2063** [comment]
I've created the initial layout for input and results in the Creation Branch. Please review.

**Comment by Tex2063** [comment]
I couldn't figure out how to get get to the Rotten Tomatoes API so I've switched everything over to OMDB. We can reference the Class Repo > 06 Ajax > Activities. This will allow us to streamline API calls and have a point of reference for code.

**Comment by Tex2063** [comment]
Please keep in mind the current styling for the page is all placeholder. Current implementation is just to clearly define sections and boxes where we will insert results.

**Comment by Tex2063** [comment]
What do we think about the possibility of using Tables instead of the divs? I think tables would allow us to insert data easier, I'm not sure. though.

**Review by kaan14 — APPROVED** [review]
approved

**Comment by Tex2063** [comment]
FINALLY! Thank you.

**Pull request merged**
